### ISSUE TITLE
xpath is required.

### ISSUE THREAD

**Issue by JawadTlais** [rafaeltonholo/svg-to-compose#6]
whay i get this error

**Comment by rafaeltonholo** [comment]
Hi @JawadTlais, the current implementation of the script relies on a few common tools that are already installed on macOS. These tools include `xpath`, `sed`, `grep`, `perl`, and so on.

You are receiving this error because your system does not have `xpath` installed, which is required for the script to run.

I am in the process of migrating the script to another language to have better support for SVG tags, and it will have fewer dependencies than it currently has.

While the update is not yet available, you can try installing all the required dependencies that the current script needs.

If you provide me with your operating system, I can try to help you.

Thank you.

**Comment by stefencookwnzl** [comment]
I have a similar issue in a Jenkins CI pipeline where we run the script to convert a number of SVG's associated with different themes in a design system we have. As part of the process we extract the SVG from Figma, and parse the SVG's in the different build pipelines we have for web, iOS and Android. Currently working with the dev ops team to see if xpath is installed on the server. Be nice if we could avoid is. I had hoped running the unoptimized flag would allow us to process with testing a POC, however we can't get around it at this point.
